# Generated by Django 5.0.6 on 2024-05-22 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(blank=True, null=True)),
                ('loan_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Station_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_station_name', models.CharField(max_length=100)),
                ('daily_target', models.IntegerField()),
                ('monthly_target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField()),
                ('due_date', models.DateField()),
                ('loan_code', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('loan_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loan_status')),
                ('customer_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit_station_names')),
            ],
        ),
    ]
